image: marthym/hugulp:1.0.0

before_script:
  - npm install

pages:
  stage: deploy
  script:
  - gulp prod
  - hugo build
  - find public -type f -iregex '.*\.\(htm\|html\|txt\|text\|js\|css\|json\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
    - public
  only:
  - master
