# Site settings
title: wiki.ght1pc9kc
email: your-email@domain.com
description: >
  Wiki perso de Marthym

baseurl:          "" # the subpath of your site, e.g. /blog/
lang:             fr_FR
timezone:         Europe/Paris
url:              https://wiki.ght1pc9kc.fr # the base hostname & protocol for your site

social:
  name: Marthym
  links:
    - https://www.linkedin.com/in/combesfrederic/
    - https://plus.google.com/+BenBalter
    - https://plus.google.com/+Fr%C3%A9d%C3%A9ricCombes
    - https://github.com/Marthym

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: superhero

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md

defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path:output_ext
    output: true
  tags:
    permalink: /:collection/:path:output_ext
    output: true
