languageCode = "fr-fr"
title = "wiki.ght1pc9kc.fr"
theme = "ght1pc9kc"
uglyurls = true

pygmentsCodefences=true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableHomeIcon = true

[markup.goldmark.renderer]
unsafe= true
