# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ght1pc9kc"
license = "WTFPL"
licenselink = "http://www.wtfpl.net/"
description = "Documentation theme for Hugo"
homepage = "http://blog.ght1pc9kc.fr/"
repo = "https://github.com/vjeantet/hugo-theme-docdock"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = 0.1

[author]
  name = "Valere JEANTET"
  homepage = "http://vjeantet.fr/"

[original]
  name = "Learn"
  homepage = "https://matcornic.github.io/hugo-learn-doc/basics/what-is-this-hugo-theme/"
  repo = "https://github.com/matcornic/hugo-theme-learn"
  licenselink = "https://github.com/matcornic/hugo-theme-learn/blob/master/LICENSE.md"